name: rosi_py
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.1=openblas
  - ipykernel=4.8.2=py36_0
  - ipython=6.2.1=py36_1
  - ipython_genutils=0.2.0=py36_0
  - jinja2=2.10=py36_0
  - jupyter=1.0.0=py36_0
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_0
  - jupyter_core=4.4.0=py_0
  - matplotlib=2.2.0=py36_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - notebook=5.4.0=py36_0
  - numpy=1.14.2=py36_blas_openblas_200
  - openblas=0.2.20=7
  - pip=9.0.1=py36_1
  - python=3.6.4=0
  - scipy=1.0.0=py36_blas_openblas_201
  - seaborn=0.8.1=py36_0
  - pip:
    - cython==0.27.3
    - pystan==2.17.1.0
